SAS_VERSION = "0.47b";
SAS_TITLE = "Simple Action Sets "..SAS_VERSION;

-- Default (enUS) strings ---------------------------------------------------

SAS_OPTIONS_TITLE="SAS Options";
SAS_OPTIONS_CLOSE="Close";
SAS_OPTIONS_BUTPOS="Position on Minimap";
SAS_OPTIONS_OFFSET="Offset position";

SAS_TEXT_CURRENT = "Loaded Actions";
SAS_TEXT_SAVEDSETS = "Saved Action Sets";
SAS_TEXT_DELETE = "Delete Set";
SAS_TEXT_SAVE = "Save Set";
SAS_TEXT_SAVEAS = "Save Set As";
SAS_TEXT_LOADCURRENT = "Load Live Actions";
SAS_TEXT_SWAPSET = "Apply Set";
SAS_TEXT_CLEARSET = "Clear Current Set";
SAS_TEXT_LOADSET = "Load Set";

SAS_TEXT_CB_ALLBARS = "Toggle all bars"
SAS_TEXT_CB_ALLBARS_LABEL = "Check All Bars"

SAS_TEXT_TAB_SETS = "Action Sets";
SAS_TEXT_TAB_OPTIONS = "Options";
SAS_TEXT_TAB_HELP = "Help";

SAS_TEXT_WARNING_TITLE = "Warning";
SAS_TEXT_WARNING_UNSAVED_LOAD = "You have unsaved changes, are you sure you want to load over them?";
SAS_TEXT_WARNING_UNSAVED_CANCEL = "You have unsaved changes, are you sure you want to close this window and lose those changes?";
SAS_TEXT_WARNING_DELETE = "You are about to delete set '|cffffffff%s|r'.\nDo you really want to delete this set?";
SAS_TEXT_WARNING_SAVE = "You are about to save changes to set '|cffffffff%s|r'";
SAS_TEXT_WARNING_SWAPPING = "You are about to apply this set to your action buttons, do you really want to do this?";
SAS_TEXT_WARNING_SWAPPINGSAVE = "You are about to save set '|cffffffff%s|r' and to apply it to your action buttons, do you really want to do this?";
SAS_TEXT_WARNING_CHANGEDSINCELAST = "Your actions appear to have been changed since last time you played.  Do you want to attempt to reset them?";
SAS_TEXT_WARNING_OKAY = "Okay";
SAS_TEXT_WARNING_CANCEL = "Cancel";

SAS_TEXT_OPTIONS_MINIMAP_HEADER = "Minimap Button";
SAS_TEXT_OPTIONS_GENERAL_HEADER = "General Options";
SAS_TEXT_OPTIONS_DEFAULT = "Default";
SAS_TEXT_OPTIONS_UNDO = "Undo";
SAS_TEXT_OPTIONS_MINIMAP_SHOW = "Show the minimap button";
SAS_TEXT_OPTIONS_MINIMAP_DRAG = "Lock the minimap button";
SAS_TEXT_OPTIONS_GENERAL_WARNINGS = "Show warnings frame";
SAS_TEXT_OPTIONS_GENERAL_WARNINGS_TOOLTIP = "Toggle the warning pop up for saving or deleting sets."
SAS_TEXT_OPTIONS_GENERAL_EMPTYBARS = "Don't apply empty bars";
SAS_TEXT_OPTIONS_GENERAL_EMPTYBARS_TOOLTIP = "Automatically disable applying of empty action bars in the set.";
SAS_TEXT_OPTIONS_GENERAL_EMPTYBUTTONS = "Don't apply empty buttons";
SAS_TEXT_OPTIONS_GENERAL_EMPTYBUTTONS_TOOLTIP = "Automatically disable applying of empty action buttons in the set.";
SAS_TEXT_OPTIONS_GENERAL_FAKEITEMTOOLTIPS = "Show generated action tooltips";
SAS_TEXT_OPTIONS_GENERAL_FAKEITEMTOOLTIPS_TOOLTIP = "Display extra tooltip information on empty item actions being generated by SAS on the action bar.";
SAS_TEXT_OPTIONS_GENERAL_AUTORESTORE = "Auto restore actions";
SAS_TEXT_OPTIONS_GENERAL_AUTORESTORE_TOOLTIP = "Attempt to automatically restore your actions to the same as the last time you logged off each time you log in to the game. (Useful a character that multiple people play on different computers.)";
SAS_TEXT_OPTIONS_GENERAL_AUTORESTOREWARN = "Warn on auto restore"
SAS_TEXT_OPTIONS_GENERAL_AUTORESTOREWARN_TOOLTIP = "Toggle the warning pop up for auto restoring your actions.";

SAS_TEXT_HELP_HEADER = "Simple Action Sets Help";
SAS_TEXT_HELP_INTRO = "This will eventually be the help file for this addon."
SAS_TEXT_HELP_TEXT = "Action set controls -\n Action Set Slots\n  Click or drag to pick up the action.\n  Click or drop on another action to move the action.\n  Drag or right click the off the Simple Action Sets frame to delete it.\n  Hold down shift and click to copy an action.\n  Hold down control and click to delete an action.\n\n Action Set Bars\n  Click or drag the bar id button to pick up the action bar.\n  Click or drop on a bar id button to swap action bars.\n  Hold down shift and click to copy an action bar.\n  Hold down control and click to delete an action bar.\n\n Action Set Bar Check Buttons\n  Disabling an action bar with the check button will tell the system not to apply this entire bar when applying actions sets.\n\nAdditional information -\n Any bar that is unchecked or empty will not be swapped. If a bar has actions, but some actions are empty, those actions will be cleared. You can alter this behavior from the options tab.\n Items you have will show up with a green border (like the one shown on the action bars when you have an item equipped).  If you do not have the item, the button will show up dimed with a red border.\n \n Swapping a large number of actions is SLOW and will cause a hitch.  The fewer number of actions swapped different from those already on the game's action bars the faster it'll be.  Turning off as many action bars in the set as possible will also increase the speed of the swap.\n \n Actions sets can be swapped either from the Simple Action Sets' Action Sets menu, or by right clicking on the SAS minimap button and selecting the set there.  It can also be put in to a macro by calling the set with /sas swap setname.\n";

SAS_TEXT_BARS_0 = "Main ActionBar";
SAS_TEXT_BARS_1 = "ActionBar Page 2";
SAS_TEXT_BARS_2 = "ActionBar Page 3\nRight ActionBar";
SAS_TEXT_BARS_3 = "ActionBar Page 4\nRight ActionBar 2";
SAS_TEXT_BARS_4 = "ActionBar Page 5\nBottom Right ActionBar";
SAS_TEXT_BARS_5 = "ActionBar Page 6\nBottom Left ActionBar";
SAS_TEXT_BARS_6 = "Battle Stance\nDruid Cat\nRogue Stealth";
SAS_TEXT_BARS_7 = "Defensive Stance";
SAS_TEXT_BARS_8 = "Berserker Stance\nDruid Bear";
SAS_TEXT_BARS_9 = "Unused";

SAS_TEXT_SAVING = "Saving set ";
SAS_TEXT_DELETING = "Deleting set ";

SAS_TEXT_CONSOLE_HELP = SAS_TITLE.."\nValid console commands -\n|iswap setname|r - swaps to a specified set name if it exists.\n|isave setname|r - saves your current actions to a specified set name.\n|ishow|r or nothing - shows the SAS options frame."
SAS_TEXT_CONSOLE_NOVALID = "No valid set named '%s' found.";

SAS_TEXT_DROPDOWN_TITLE = "Options";
SAS_TEXT_DROPDOWN_OPEN = "Open Sets Frame"
SAS_TEXT_DROPDOWN_SAVENEW = "Save New Set";
SAS_TEXT_DROPDOWN_SAVECURRENT = "Save Current Set";
SAS_TEXT_DROPDOWN_SETS = "Apply Action Sets";
SAS_TEXT_DROPDOWN_NONE = "No sets";

SAS_TEXT_TOOLTIP_NOMACRO = "Macro cannot be found.";
SAS_TEXT_TOOLTIP_NOTHAVE = "Item cound not be found.";
SAS_TEXT_TOOLTIP_NOTVALID = "Item could not be found, unable to generate tooltip.";
SAS_TEXT_TOOLTIP_NOSPELL = "Spell could not be found.";
SAS_TEXT_TOOLTIP_NOSPELLRANK = "Could not find %r of this spell. Will use highest existing rank.";
SAS_TEXT_TOOLTIP_FAKEACTIONWARN = "|c00ff0000Picking up or replacing this action will remove it from the action button.";
SAS_TEXT_TOOLTIP_GENERATEDACTION = "This action is generated by <|cff40E0D0SAS|r>";

-- Save menu (previously hardcoded in XML)
SAS_TEXT_SAVEMENU_TITLE = "Save New Set As";
SAS_TEXT_SAVEMENU_EDITING = "Type in the name of the new set:";
SAS_TEXT_SAVEMENU_INUSE = "This name is already used by another set.";
SAS_TEXT_SAVEMENU_NONAME = "|cffff0000You must enter a name for the new set.";
SAS_TEXT_SAVEMENU_EXISTS = "|cffff0000This set already exists, save over it?";

-- Minimap tooltip text (previously hardcoded in SimpleActionSets.lua)
SAS_TEXT_MINIMAP_LOCKED = " Minimap button is locked";
SAS_TEXT_MINIMAP_RESET = " Right click SAS button to reset";
SAS_TEXT_MINIMAP_DRAGHINT = " Drag to reposition minimap button";

-- Goblin Brainwashing Device support (Weird Vibes server feature).
SAS_BRAINWASHER_NAME = "Goblin Brainwashing Device";
SAS_BRAINWASHER_SAVE_PATTERN = "Save (%d+)(..) Specialization";
SAS_BRAINWASHER_LOAD_PATTERN = "Activate (%d+)(..) Specialization %((%d+)/(%d+)/(%d+)%)";
SAS_BRAINWASHER_SAVE_SIMPLE_PATTERN = "Save (%d+).. Specialization";
SAS_BRAINWASHER_LOAD_SIMPLE_PATTERN = "Activate (%d+).. Specialization";
SAS_BRAINWASHER_SAVE_LABEL_FMT = "Save %d%s Specialization - ACTIVE ACTIONBARS";
SAS_BRAINWASHER_LOAD_LABEL_FMT = "Activate %d%s Specialization (%s/%s/%s) - ACTIVE TALENTS";


----------------------
-- Titan Panel text --
----------------------

SAS_TITAN_ID = "SAS";
SAS_TITAN_LABEL = "Current Set: ";
SAS_TITAN_NA = "n/a";
SAS_TITAN_HINT = "Hint: Left-click to open sets frame."


----------------------
-- Locale overrides --
----------------------

local locale = GetLocale and GetLocale() or "enUS";

if locale == "zhCN" then
	SAS_TITLE = "Simple Action Sets "..SAS_VERSION;

	SAS_OPTIONS_TITLE = "SAS 选项";
	SAS_OPTIONS_CLOSE = "关闭";
	SAS_OPTIONS_BUTPOS = "小地图位置";
	SAS_OPTIONS_OFFSET = "位置偏移";

	SAS_TEXT_CURRENT = "当前动作";
	SAS_TEXT_SAVEDSETS = "已保存的动作集";
	SAS_TEXT_DELETE = "删除动作集";
	SAS_TEXT_SAVE = "保存动作集";
	SAS_TEXT_SAVEAS = "另存为动作集";
	SAS_TEXT_LOADCURRENT = "加载当前动作";
	SAS_TEXT_SWAPSET = "应用动作集";
	SAS_TEXT_CLEARSET = "清空当前动作集";
	SAS_TEXT_LOADSET = "加载动作集";

	SAS_TEXT_CB_ALLBARS = "切换所有动作条";
	SAS_TEXT_CB_ALLBARS_LABEL = "全选动作条";

	SAS_TEXT_TAB_SETS = "动作集";
	SAS_TEXT_TAB_OPTIONS = "选项";
	SAS_TEXT_TAB_HELP = "帮助";

	SAS_TEXT_WARNING_TITLE = "警告";
	SAS_TEXT_WARNING_UNSAVED_LOAD = "您有尚未保存的修改，确定要加载并覆盖它们吗？";
	SAS_TEXT_WARNING_UNSAVED_CANCEL = "您有尚未保存的修改，确定要关闭窗口并放弃这些修改吗？";
	SAS_TEXT_WARNING_DELETE = "您即将删除动作集 '|cffffffff%s|r'。\n确定要删除此动作集吗？";
	SAS_TEXT_WARNING_SAVE = "您即将保存对动作集 '|cffffffff%s|r' 的修改";
	SAS_TEXT_WARNING_SWAPPING = "您即将把此动作集应用到您的动作条上，确定要这么做吗？";
	SAS_TEXT_WARNING_SWAPPINGSAVE = "您即将保存动作集 '|cffffffff%s|r' 并将其应用到您的动作条上，确定要这么做吗？";
	SAS_TEXT_WARNING_CHANGEDSINCELAST = "您的动作条似乎自上次游戏后被改动过。要尝试将其重置吗？";
	SAS_TEXT_WARNING_OKAY = "确定";
	SAS_TEXT_WARNING_CANCEL = "取消";

	SAS_TEXT_OPTIONS_MINIMAP_HEADER = "小地图按钮";
	SAS_TEXT_OPTIONS_GENERAL_HEADER = "通用选项";
	SAS_TEXT_OPTIONS_DEFAULT = "默认";
	SAS_TEXT_OPTIONS_UNDO = "撤销";
	SAS_TEXT_OPTIONS_MINIMAP_SHOW = "显示小地图按钮";
	SAS_TEXT_OPTIONS_MINIMAP_DRAG = "锁定小地图按钮";
	SAS_TEXT_OPTIONS_GENERAL_WARNINGS = "显示警告窗口";
	SAS_TEXT_OPTIONS_GENERAL_WARNINGS_TOOLTIP = "在保存或删除动作集时显示警告弹窗。";
	SAS_TEXT_OPTIONS_GENERAL_EMPTYBARS = "不应用空动作条";
	SAS_TEXT_OPTIONS_GENERAL_EMPTYBARS_TOOLTIP = "自动跳过动作集中的空动作条。";
	SAS_TEXT_OPTIONS_GENERAL_EMPTYBUTTONS = "不应用空按钮";
	SAS_TEXT_OPTIONS_GENERAL_EMPTYBUTTONS_TOOLTIP = "自动跳过动作集中的空动作按钮。";
	SAS_TEXT_OPTIONS_GENERAL_FAKEITEMTOOLTIPS = "显示生成的动作提示";
	SAS_TEXT_OPTIONS_GENERAL_FAKEITEMTOOLTIPS_TOOLTIP = "在动作条上由 SAS 生成的空物品动作上显示额外的提示信息。";
	SAS_TEXT_OPTIONS_GENERAL_AUTORESTORE = "自动恢复动作";
	SAS_TEXT_OPTIONS_GENERAL_AUTORESTORE_TOOLTIP = "每次登录游戏时，尝试将动作自动恢复到上次登出时的状态。（适合多人共用一个角色但使用不同电脑的情况。）";
	SAS_TEXT_OPTIONS_GENERAL_AUTORESTOREWARN = "自动恢复时弹出警告";
	SAS_TEXT_OPTIONS_GENERAL_AUTORESTOREWARN_TOOLTIP = "切换自动恢复动作时的警告弹窗。";

	SAS_TEXT_HELP_HEADER = "Simple Action Sets 帮助";
	SAS_TEXT_HELP_INTRO = "这里将会是本插件的帮助文档。";
	SAS_TEXT_HELP_TEXT = "动作集操作 -\n 动作集格子\n  点击或拖动以拾取动作。\n  点击或拖到另一格上以移动该动作。\n  右键或将其拖出 Simple Action Sets 窗口即可删除。\n  按住 Shift 键并点击可复制动作。\n  按住 Ctrl 键并点击可删除动作。\n\n 动作集动作条\n  点击或拖动动作条编号按钮以拾取整个动作条。\n  点击或拖到另一个动作条编号上以交换动作条。\n  按住 Shift 键并点击可复制动作条。\n  按住 Ctrl 键并点击可删除动作条。\n\n 动作条复选框\n  取消勾选某个动作条后，应用动作集时将整体跳过该动作条。\n\n附加说明 -\n 任何被取消勾选或为空的动作条都不会被应用。如果动作条上有动作但其中某些位置为空，那些空位会被清空。可以在“选项”页中修改此行为。\n 您拥有的物品会以绿色边框显示（与装备物品时动作条上的显示相同）。若您没有该物品，按钮会变暗并以红色边框显示。\n \n 一次切换大量动作会很慢并造成卡顿。需要切换的动作越少（即与当前动作条差异越少），切换速度越快。在动作集中关闭尽可能多的动作条也能提升切换速度。\n \n 动作集既可以通过 Simple Action Sets 的“动作集”菜单切换，也可以通过右键点击 SAS 小地图按钮并在其中选择。也可以通过宏 /sas swap 动作集名称 来应用。\n";

	SAS_TEXT_BARS_0 = "主动作条";
	SAS_TEXT_BARS_1 = "动作条 2";
	SAS_TEXT_BARS_2 = "动作条 3\n右侧动作条";
	SAS_TEXT_BARS_3 = "动作条 4\n右侧动作条 2";
	SAS_TEXT_BARS_4 = "动作条 5\n右下动作条";
	SAS_TEXT_BARS_5 = "动作条 6\n左下动作条";
	SAS_TEXT_BARS_6 = "战斗姿态\n德鲁伊豹形\n潜行";
	SAS_TEXT_BARS_7 = "防御姿态";
	SAS_TEXT_BARS_8 = "狂暴姿态\n德鲁伊熊形";
	SAS_TEXT_BARS_9 = "未使用";

	SAS_TEXT_SAVING = "正在保存动作集 ";
	SAS_TEXT_DELETING = "正在删除动作集 ";

	SAS_TEXT_CONSOLE_HELP = SAS_TITLE.."\n可用命令 -\n|iswap 动作集名称|r - 切换到指定名称的动作集（若存在）。\n|isave 动作集名称|r - 将当前动作保存为指定名称的动作集。\n|ishow|r 或不带参数 - 显示 SAS 选项窗口。";
	SAS_TEXT_CONSOLE_NOVALID = "找不到名为 '%s' 的动作集。";

	SAS_TEXT_DROPDOWN_TITLE = "选项";
	SAS_TEXT_DROPDOWN_OPEN = "打开动作集窗口";
	SAS_TEXT_DROPDOWN_SAVENEW = "保存为新动作集";
	SAS_TEXT_DROPDOWN_SAVECURRENT = "保存当前动作集";
	SAS_TEXT_DROPDOWN_SETS = "应用动作集";
	SAS_TEXT_DROPDOWN_NONE = "暂无动作集";

	SAS_TEXT_TOOLTIP_NOMACRO = "找不到对应的宏。";
	SAS_TEXT_TOOLTIP_NOTHAVE = "找不到该物品。";
	SAS_TEXT_TOOLTIP_NOTVALID = "找不到该物品，无法生成提示。";
	SAS_TEXT_TOOLTIP_NOSPELL = "找不到该法术。";
	SAS_TEXT_TOOLTIP_NOSPELLRANK = "找不到该法术的 %r 等级，将使用现有最高等级。";
	SAS_TEXT_TOOLTIP_FAKEACTIONWARN = "|c00ff0000拾取或替换此动作将其从动作按钮上移除。";
	SAS_TEXT_TOOLTIP_GENERATEDACTION = "此动作由 <|cff40E0D0SAS|r> 生成";

	SAS_TEXT_SAVEMENU_TITLE = "另存为新动作集";
	SAS_TEXT_SAVEMENU_EDITING = "请输入新动作集的名称：";
	SAS_TEXT_SAVEMENU_INUSE = "此名称已被另一个动作集使用。";
	SAS_TEXT_SAVEMENU_NONAME = "|cffff0000请为新动作集输入一个名称。";
	SAS_TEXT_SAVEMENU_EXISTS = "|cffff0000此动作集已存在，是否覆盖？";

	SAS_TEXT_MINIMAP_LOCKED = " 小地图按钮已锁定";
	SAS_TEXT_MINIMAP_RESET = " 右键点击 SAS 按钮可重置位置";
	SAS_TEXT_MINIMAP_DRAGHINT = " 拖动可调整小地图按钮位置";

	SAS_TITAN_LABEL = "当前动作集：";
	SAS_TITAN_NA = "无";
	SAS_TITAN_HINT = "提示：左键点击可打开动作集窗口。";

	-- Brainwasher
	SAS_BRAINWASHER_NAME = "地精洗脑装置";
	SAS_BRAINWASHER_SAVE_PATTERN = "保存第(%d+)(.-)天赋";
	SAS_BRAINWASHER_LOAD_PATTERN = "启用第(%d+)(.-)天赋.-%((%d+)/(%d+)/(%d+)%)";
	SAS_BRAINWASHER_SAVE_SIMPLE_PATTERN = "保存第(%d+).-天赋";
	SAS_BRAINWASHER_LOAD_SIMPLE_PATTERN = "启用第(%d+).-天赋";
	SAS_BRAINWASHER_SAVE_LABEL_FMT = "保存第%d%s天赋 - 当前动作条";
	SAS_BRAINWASHER_LOAD_LABEL_FMT = "启用第%d%s天赋 (%s/%s/%s) - 当前天赋";
end
